### PR TITLE
Removed unused scripts and changes grade to stable

### PR DESCRIPTION
**Pull request by Vs-karma**
XSNAP-5: there are multiple scripts and jar files that may remain unused or are now obsolete.
Check the [snapcraft.yaml](https://github.com/xwiki-contrib/packaging-snap/blob/main/xwiki-jetty/stable/snapcraft.yaml) to see the files being used 

Removed Unused copy.sh and update.sh from both stable and edge since they were unused

### CODE REVIEW

**Review by VedantPol — APPROVED** [review]
looks good to me

**Comment by vmassol** [comment]
thanks! Note: the commit message is missing a reference to the jira issue. See https://dev.xwiki.org/xwiki/bin/view/Community/DevelopmentPractices#HRule:AlwaysputaJIRAissuereferenceincommitmessages

**Comment by tmortagne** [comment]
>  the commit message is missing a reference to the jira issue

My understanding is that this pull request is only build cleanup without any actual functional impact (which generally does not worth a jira issue).

**Comment by vmassol** [comment]
ok then, my bad, thanks @tmortagne 

EDIT: changing the grade to stable doesn't seem something that small though ;)

**Comment by VedantPol** [comment]
hey, @vmassol  changing grade doesn't actually affect the functionality much it's just a requirement for stable and candidate channel on snapcraft store . anyways I have created two  Jira issues  for the following  :)

**Comment by Vs-karma** [comment]
XSNAP-6: Defines the quality grade of the snap.
Type: enum
Can be either devel (i.e. a development version of the snap, so not to be published to the stable or candidate channels) or stable (i.e. a stable release or release candidate, which can be released to all channels)
Example: {{[stable}} or \{{devel}}]
To publish snap on the candidate channel stable grade is required Thus change all  the snap to stable grade

Changed the grade to stable so that it can be published on the candidate channel.

**Pull request merged**
